//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopee.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Administrator
    {
        public System.Guid Id { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Picture { get; set; }
        public string Email { get; set; }
        public Nullable<System.Guid> GroupId { get; set; }
    
        public virtual Group Group { get; set; }
    }
}
